name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test_render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: render tools
        shell: bash -l {0}
        run: |
          conda install pyyaml
          make render
