name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test_render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: render tools
        run: make render
