name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test_render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: render tools
        run: make render
