name: render_tools

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: render tools
        shell: bash -l {0}
        run: |
          conda install pyyaml
          make render

      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated tools
          committer: q2d2 <q2d2.noreply@gmail.com>
          title: Automated re-render of Galaxy Tools
          body: Results of `make render` on `main`
